#config.yaml
problem_type: 'classification'

preprocessing:
  test_size: 0.2
  nsplit: 5

ensemble_list: ['LGBM','RF', 'XGBoost', 'CatBoost']

OPTUNA: True

hypopt:
  n_trials: 5

NAS:

features:
  no_feature: True
  custom_feature: False
  auto_feature: False
  ext_feature: False

random_state: 42

target_col: 'Class'

selected_model: '2023-03-28-20-23-28'

data_dir: 'data/'
model_dir: 'models/'
input_filepath: 
output_filepath: 