#config.yaml
competition_name: 'playground-series-s3e17'
problem_type: 'classification'
metric: 'neg_log_loss'
direction: 'maximize'
target_col: 'Class'

preprocessing:
  imputer:
  test_size: 0.2
  nsplit: 5

ensemble_list: ['XGBoost','RF', 'CatBoost','LGBM']

OPTUNA: True

retrain: True

hypopt:
  n_trials: 20

NAS: False

features:
  no_feature: False
  custom_feature: True
  auto_feature: True
  ext_feature: False
  pca_feature: False
  scaler: True

random_state: 42
selected_model: '2023-06-21-10-09-38' #modify after running make train
data_dir: 'data/'
model_dir: 'models/'
input_filepath: 
output_filepath: 