#config.yaml
competition_name: 'generative_ai_dataset'
problem_type: 'classification'
metric: 'f1'
direction: 'maximize'
target_col: 'labels'
predictions_format: 'class'

preprocessing:
  imputer:
  test_size: 0.2
  nsplit: 5
  drop_columns : []

ensemble_list: ['XGBoost', 'NN', 'Autoencoder','RF', 'CatBoost','LGBM']

OPTUNA: True

retrain: True

hypopt:
  n_trials: 20

NAS: False

features:
  no_feature: False
  custom_feature: False
  auto_feature: False
  ext_feature: False
  pca_feature: False
  scaler: True

new_feature_count: 5 #only if auto_feature is True

random_state: 42
selected_model: '2023-07-18-16-03-33' #modify after running make train
data_dir: 'data/'
model_dir: 'models/'
input_filepath: 
output_filepath: 