#config.yaml
competition_name: 'playground-series-s3e7'
problem_type: 'classification'
metric: 'roc_auc'
direction: 'maximize'
target_col: 'booking_status'

preprocessing:
  imputer:
  test_size: 0.2
  nsplit: 5
  drop_columns:  #None if no column dropped

ensemble_list: [  'NN','LGBM','XGBoost','RF','CatBoost']

OPTUNA: True

retrain: True

hypopt:
  n_trials: 20

NAS: False

features:
  no_feature: False
  custom_feature: False
  auto_feature: False
  ext_feature: False
  pca_feature: False
  scaler: True

random_state: 42
selected_model: '2023-07-15-20-53-28' #modify after running make train
data_dir: 'data/'
model_dir: 'models/'
input_filepath: 
output_filepath: 