#config.yaml
competition_name: 'playground-series-s3e10'
problem_type: 'classification'
metric: 'neg_log_loss'
direction: 'maximize'
target_col: 'Class'
predictions_format: 'proba'

preprocessing:
  imputer:
  test_size: 0.2
  nsplit: 5
  drop_columns : []

ensemble_list: ['XGBoost', 'NN', 'Autoencoder','RF', 'CatBoost','LGBM']

OPTUNA: True

retrain: True

hypopt:
  n_trials: 20

NAS: False

features:
  no_feature: False
  custom_feature: False
  auto_feature: True
  ext_feature: False
  pca_feature: False
  scaler: True

new_feature_count: 3 #only if auto_feature is True

random_state: 42
selected_model: '2023-07-22-12-06-27' #modify after running make train
data_dir: 'data/'
model_dir: 'models/'
input_filepath: 
output_filepath: 